#!/bin/bash

directory=$(find ~/projects/code -maxdepth 2 -type d | fzf | tr . _)

if pgrep tmux
then
    if tmux has-session -t $directory
    then
        if [ -v TMUX ]
        then
            tmux switch-client -t "$directory"
        else
            tmux a -t "$directory"
        fi
    else
        tmux new -dc "$directory" -s "$directory"
        if [ -v TMUX ]
        then
            tmux switch-client -t "$directory"
        else
            tmux a
        fi
    fi
else
    tmux new -dc "$directory" -s "$directory"
    tmux a
fi
