#!/bin/bash

directory="$(find ~/projects/code ~/.config -maxdepth 2 -type d | fzf)"
name="$(echo "$directory" | tr '.' '_')"

pgrep tmux
if [[ $? != 0 ]]
then
    tmux start-server
fi

tmux has-session -t "=$name"
if [[ $? != 0 ]]
then
    tmux new -dc "$directory" -s "$name"
fi

tmux a -t "=$name"

